ecommerceproj/ecommerceproj/urls.py
from django.contrib import admin
from django.urls import path
from ecommerceapp import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home_view'),
    path('reg',views.Register.as_view(),name='reg_view'),
    path('log',views.LoginView.as_view(),name='log_view'),
    path('logout',views.LogoutView.as_view(),name='logout_view'),
    path('product/detail/<int:id>',views.ProductDetailView.as_view(),name='detail_view'),
    path('add/cart/<int:id>',views.AddToCartView.as_view(),name='addcart_view'),
    path('cartlist',views.CartListView.as_view(),name='cartlist_view'),
    path('place/order/<int:cart_id>',views.PlaceOrderView.as_view(),name='placeorder_view'),
    path('cart/delete/<int:id>',views.CartDeleteView.as_view(),name='cartdelete_view'),




    


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproj/ecommerceapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    category_name=models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)
     
    def __str__(self):
        return self.category_name
    
class Products(models.Model):
    product_name=models.CharField(max_length=100)
    price=models.PositiveIntegerField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='image',null=True)
    description=models.CharField(max_length=100)

    def __str__(self):
        return self.product_name
    
class Carts(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)
    options=(
        ('in-cart','in-cart'),
        ('cancelled','cancelled'),
        ('order-placed','order-placed'),
    )
    status=models.CharField(max_length=100,choices=options,default='in-cart')

class Orders(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cart=models.ForeignKey(Carts,on_delete=models.CASCADE)
    order_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField(max_length=255)
    email=models.EmailField(max_length=255)
    options=(
        ('order-placed','order-placed'),
        ('cancelled','cancelled'),
        ('dispatched','dispatched'),
        ('delivered','delivered')
    )
    status=models.CharField(max_length=100,choices=options,default='order-placed')

ecommerceproj/ecommerceapp/forms.py
from django import forms
from django.contrib.auth.models import User
from ecommerceapp.models import Carts,Orders

class UserRegisterForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password','email']
        widgets={
           'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your FirstName'}),
           'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your LastName'}),
           'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your UserName'}),
           'password':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Pssword'}),
           'email':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Email'}),
        }

class LoginForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password']
        widgets={'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your UserName'}),
           'password':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Pssword'})

        }

class CartForm(forms.ModelForm):
    class Meta:
        model=Carts
        fields=['quantity']
        widgets={
            'quantity':forms.NumberInput(attrs={'class':'form-control'})
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model=Orders
        fields=['address','email']
        widgets={
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'})


        }
        

ecommerceproj/ecommerceapp/views.py
from django.shortcuts import render,redirect
from django.views import View
from ecommerceapp.forms import UserRegisterForm,LoginForm,CartForm,OrderForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from ecommerceapp.models import Products,Carts,Orders
from django.core.mail import send_mail,settings
# Create your views here. 

class Home(View):
    def get(self,request):
        data=Products.objects.all()
        return render (request,'index.html',{'products':data})
    
class Register(View):
    def get(self,request):
        form  = UserRegisterForm()
        return render(request,'userregister.html',{'form':form})
    def post(self,request,*args,**kwargs):
        form=UserRegisterForm(request.POST)
        if form.is_valid():
            User.objects.create_user(**form.cleaned_data)
            messages.success(request,'Registration successful')
            return redirect('log_view')
        else:
            messages.error(request,'invalid')
            return redirect('home_view')

class LoginView(View):
    def get(self,request):
        form=LoginForm()
        return render(request,'login.html',{'form':form})
    def post(self,request,*args,**kwargs):
        uname=request.POST['username']
        psw=request.POST['password']
        user=authenticate(username=uname,password=psw)
        if user:
            login(request,user)
            messages.success(request,'Login successful')
            return redirect('home_view')
        else:
            messages.error(request,'Login Unsuccessful')
            return redirect('log_view')

class LogoutView(View):
    def get(self,request):
        logout(request)
        messages.success(request,'Logout Successful')
        return redirect('home_view')

class ProductDetailView(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get('id')
        product=Products.objects.get(id=id)
        return render(request,'product_detail.html',{'product_product':product})

class AddToCartView(View):
    def get(self,request,*args,**kwargs):
        form=CartForm()
        id=kwargs.get('id')
        product=Products.objects.get(id=id)       
        return render(request,'add_tocart.html',{'form':form,'product':product})
    
    def post(self,request,*args,**kwargs):
        u=request.user
        id=kwargs.get('id')
        p=Products.objects.get(id=id)
        q=request.POST.get('quantity')
        Carts.objects.create(user=u,quantity=q,product=p)
        return redirect('home_view')

class CartListView(View):
    def get(self,request,*args,**kwargs):
        cart=Carts.objects.filter(user=request.user).exclude(status='order-placed')
        return render(request,'cartlist.html',{'cart':cart})
    
class PlaceOrderView(View):
    def get(self,request,*args,**kwargs):
        form=OrderForm()
        return render(request,'place_order.html',{'form':form})
    
    def post(self,request,*args,**kwargs):
        cart_id=kwargs.get('cart_id')
        cart=Carts.objects.get(id=cart_id)
        user=request.user
        address=request.POST.get('address')
        email=request.POST.get('email')
        Orders.objects.create(user=user,cart=cart,address=address,email=email)
        send_mail("Confirmation","Order Placed Successfully",settings.EMAIL_HOST_USER,[email])
        cart.status='order-placed'
        cart.save()
        return redirect('home_view')

class CartDeleteView(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get('id')
        data=Carts.objects.get(id=id)
        data.delete()
        return redirect('cartlist_view')


  
    

ecommerceproj/ecommerceapp/templates/add_tocart.html
{% extends 'index.html' %}
{% block content %}


<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <div class="col-8">

        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="{{product.image.url}}" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{product.product_name}}</h5>
                    <!-- Product price-->
                    <h6>{{product.price}}</h6>
                    {{product.description}}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                        href="{% url 'addcart_view' product.id %}">Add to Cart</a>
                </div>

            </div>
        </div>

    </div>
    <div class="col-4">
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn btn-primary ">
        </form>
    </div>
</div>








{% endblock %}

ecommerceproj/ecommerceapp/templates/cartlist.html
{% extends 'index.html' %}

{% block content %}

<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for cart in cart %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{cart.product.image.url}}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{cart.product.product_name}}</h5>
                        <!-- Product price-->
                       {{cart.product.price}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent"> 
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'placeorder_view' cart.id %}">Place Order</a></div>
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'cartdelete_view' cart.id %}">Remove</a></div>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerceproj/ecommerceapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'reg_view' %}">Register</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'log_view' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'logout_view' %}">Logout</a></li>



                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">All Products</a></li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <a  class="btn btn-outline-dark" type="submit" href="{% url 'cartlist_view' %}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">
                            <!-- {% if request.user.carts_set.all.count > 0 %}
                            {{request.user.carts_set.all.count}}
                            {% else %}
                            0
                            {% endif %} -->

                            {{count}}


                        </span>
                    </a>
                </form>
            </div>
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}






    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>


  {% block content %}
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{product.image.url}}" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{product.product_name}}</h5>
                                <!-- Product price-->
                               {{product.price}}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent"> 
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'detail_view' product.id %}">View options</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}






    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

ecommerceproj/ecommerceapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">

    </form>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

ecommerceproj/ecommerceapp/templates/place_order.html
{% extends 'index.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="POST">
              {% csrf_token %}
              {{form}}
              <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>


{% endblock %}

ecommerceproj/ecommerceapp/templates/product_detail.html
{% extends 'index.html' %}


{% block content %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
       
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{product_product.image.url}}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product_product.product_name}}</h5>
                        <!-- Product price-->
                        <h6>{{product_product.price}}</h6>
                       {{product_product.description}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent"> 
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'addcart_view' product_product.id %}">Add to Cart</a>
                    </div>
                    
                </div>
            </div>
        </div>
      
    </div>
</div>
{% endblock %}

ecommerceproj/ecommerceapp/templates/userregister.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <!-- https://cdnjs.com/libraries/twitter-bootstrap/5.0.0-beta1 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css"
    />

    <!-- Icons: https://getbootstrap.com/docs/5.0/extend/icons/ -->
    <!-- https://cdnjs.com/libraries/font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    />

    <title>Register</title>
  </head>
  <body class="d-flex vw-100 vh-100 align-items-center justify-content-center">
    <form action="" method="POST">
        {% csrf_token %}
         {{form}}
         <input type="submit">
      </form>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.bundle.min.js"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <!-- https://cdnjs.com/libraries/popper.js/2.5.4 -->
    <!-- <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"
    ></script> -->

    <!-- More: https://getbootstrap.com/docs/5.0/getting-started/introduction/ -->
  </body>
</html>